name: Lookup Go Module Version

on:
  release:
    types:
      - published

jobs:
  lookup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Refresh Go Module Cache
        run: |
          curl https://sum.golang.org/lookup/github.com/coreybutler/go-where@${{ github.event.release.tag_name }}
