name: Refresh Go Module Cache

on:
  release:
    types:
      - published

jobs:
  lookup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract major version from release tag
        id: extract_major_version
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          MAJOR_VERSION=$(echo $TAG_NAME | sed -E 's/^v([0-9]+).*$/\1/')
          if [ "$MAJOR_VERSION" -ge 2 ]; then
            MODULE_PATH="github.com/coreybutler/go-where/v$MAJOR_VERSION"
          else
            MODULE_PATH="github.com/coreybutler/go-where"
          fi
          echo "MODULE_PATH=$MODULE_PATH" >> $GITHUB_ENV
          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV

      - name: Refresh Go Module Cache
        run: |
          curl https://sum.golang.org/lookup/$MODULE_PATH@$VERSION
